name = "Store Credit Limit"
scopes = "write_customers,read_customers,write_orders,read_orders,write_discounts,read_discounts"
api_version = "2023-10"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2023-10"

[app_preferences]
url = "/"
