name = "Store Credit Function"
type = "function"
api_version = "2023-10"

[build]
command = "npm run build"
path = "dist/function.wasm"

[ui.paths]
create = "/"
details = "/"

[function]
input_query = """
  query Input {
    cart {
      lines {
        id
        quantity
        merchandise {
          __typename
          ... on ProductVariant {
            id
            product {
              id
              title
            }
          }
        }
        cost {
          totalAmount {
            amount
            currencyCode
          }
        }
      }
      cost {
        totalAmount {
          amount
          currencyCode
        }
      }
      buyerIdentity {
        customer {
          id
          metafields(first: 10, namespace: "custom") {
            edges {
              node {
                key
                value
              }
            }
          }
        }
      }
    }
  }
"""

[function.runtime]
name = "javascript"
